print("My name is Monisha Sankar")
print("I am from  Sholavandhan")
print("My bachelors degree in Information Technology and Management from Lady Doak College")
print("My post graduation degree in computer science from Fatima College")
print("My Father name is Sankar")
print("He is Mechanic")
print("My Mother name is Janaki")
print("She is Home Maker")
print("One younger brother Shyam Sundar")
print("he completed his BTech Information Technology")
print("From velammal college")
print("My strenth are Quick Learner,Hard Working and Good in Communication Skills")
print("My weekness are trusting people easily")
print("My hobbies are Cooking ,Drawing ,Painting etc ")